fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: nicolas.tran@supinternet.fr
        sender_name: You
framework:
    # ...
    templating:
        engines: ['twig', 'php']