fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: nicolas.tran@supinternet.fr
        sender_name: You
    registration:
        form:
            type: App\Forms\RegistrationType
            validation_groups: [AppRegistration]
    profile:
        form:
            type: App\Forms\ProfileType
            validation_groups: [AppProfile]
framework:
    # ...
    templating:
        engines: ['twig', 'php']