#index:
#    path: /
#    controller: App\Controller\MainController::homepage
#addFriends:
#    path: /friends
#    controller: App\Controller\MainController::friends
#    path: /addFriends
#    controller: App\Controller\MainController::addFriends
#    path: /removeFriends
#    controller: App\Controller\MainController::removeFriends
#    path: /getUsers
#    controller: App\Controller\MainController::getUsers
#    path: /profile
#    controller: App\Controller\ProfileController::ShowAction
#    path: /profile/edit
#    controller: App\Controller\ProfileController::ShowAction
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
